module.exports = {
  picture: {
    white: {
      king: '♔',
      queen: '♕',
      rook: '♖',
      bishop: '♗',
      knight: '♘',
      pawn: '♙',
      'nightrider': '💂🏻',
      'cannon': '👈🏻',
      'bloodlust': '👰🏻',
      'bomber': '👳🏻',
      'dabbaba': '👴🏻',
      'alfil': '🐘',
      'wazir': '👵🏻',
      'ferz': '👮🏻',
      'archbishop': '🎅🏻',
      'empress': '👸🏻',
      'berolina': '💁🏻',
      'shapeshifter': '👻'
    },
    black: {
      king: '♚',
      queen: '♛',
      rook: '♜',
      bishop: '♝',
      knight: '♞',
      pawn: '♟',
      'nightrider': '💂🏿',
      'cannon': '👈🏿',
      'bloodlust': '👰🏿',
      'bomber': '👳🏿',
      'dabbaba': '👴🏿',
      'alfil': '🐘',
      'wazir': '👵🏿',
      'ferz': '👮🏿',
      'archbishop': '🎅🏿',
      'empress': '👸🏿',
      'berolina': '💁🏿',
      'shapeshifter': '👻'
    }
  },
  description: {
    king: 'Moves like a normal chess King. Must be captured to lose the game.',
    queen: 'Moves like a normal chess Queen.',
    rook: 'Moves like a normal chess Rook.',
    bishop: 'Moves like a normal chess Bishop.',
    knight: 'Moves like a normal chess Knight.',
    pawn: 'Moves like a normal chess Pawn.',
    nightrider: 'A powerful piece that loves like a knight an unlimited number of times in one direction.',
    'cannon': 'Although limited in mobility, it can capture pieces from afar.',
    'bloodlust': 'It\'s mobility increases as it captures oponents.',
    'bomber': 'Has the ability to detonate, destroying any piece in a one piece radius.',
    'dabbaba': 'A medieval siege engine.',
    'alfil': 'An elephant.',
    'wazir': 'A minister.',
    'ferz': 'A Counsellor.',
    'archbishop': 'Moves like a combination Knight and Bishop.',
    'empress': 'Moves like a combination Knight and Rook.',
    'berolina': 'Moves opposite of the standard chess Pawn.',
    'shapeshifter': 'Changes into whatever piece it captures.'
  }
}

